"""Clang command-line integration for VulSOR."""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


class ClangError(RuntimeError):
    """Raised when Clang cannot produce an AST for a source file."""


@dataclass(frozen=True)
class ASTOutput:
    """Clang AST together with the source text used to produce it."""

    ast_json: str
    source: str
    source_path: str | None = None


@dataclass(frozen=True)
class ClangRunResult:
    """Output from one Clang analysis command."""

    output: str
    diagnostics: str
    recovered: bool = False


class ClangAdapter:
    """Run Clang and expose its JSON AST output."""

    def __init__(self, executable: str = "clang") -> None:
        """Initialize the adapter with a Clang executable name or path."""
        self._executable = executable

    def dump_ast(
        self,
        source_file: Path,
        *,
        allow_errors: bool = False,
        extra_args: Sequence[str] = (),
    ) -> str | ClangRunResult:
        """Return the raw JSON AST generated by Clang.

        Args:
            source_file: Path to the C or C++ source file.

        Returns:
            The raw JSON AST emitted by Clang.

        Raises:
            FileNotFoundError: If ``source_file`` does not exist.
            ClangError: If Clang cannot parse the source file or produce
                valid AST JSON.
        """
        source_file = source_file.resolve()

        if not source_file.is_file():
            raise FileNotFoundError(
                f"Source file does not exist: {source_file}"
            )

        language = self._language_for(source_file)

        command = [
            self._executable,
            "-x",
            language,
            "-Xclang",
            "-ast-dump=json",
            "-ferror-limit=0",
            "-fsyntax-only",
            *extra_args,
            str(source_file),
        ]

        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
            )
        except FileNotFoundError as exc:
            raise ClangError(
                f"Clang executable was not found: {self._executable}"
            ) from exc
        except OSError as exc:
            raise ClangError(
                f"Failed to execute Clang: {self._executable}"
            ) from exc

        output = result.stdout.strip()
        stderr = result.stderr.strip()

        if result.returncode != 0 and not allow_errors:
            stderr = result.stderr.strip()

            raise ClangError(
                "Clang failed to parse the source file."
                + (f"\n{stderr}" if stderr else "")
            )

        if not output:
            raise ClangError("Clang returned an empty AST.")

        try:
            json.loads(output)
        except json.JSONDecodeError as exc:
            raise ClangError(
                "Clang returned output that is not valid JSON AST."
            ) from exc

        if allow_errors:
            return ClangRunResult(
                output=output,
                diagnostics=stderr,
                recovered=result.returncode != 0,
            )

        return output

    def dump_ast_with_source(
        self,
        source_file: Path,
        *,
        allow_errors: bool = False,
        extra_args: Sequence[str] = (),
    ) -> ASTOutput | tuple[ASTOutput, str]:
        """Return the Clang AST together with its source text.

        The source text is retained so downstream analysis can resolve
        Clang byte offsets to source line numbers when Clang omits a line
        number from an AST location.
        """
        source_file = source_file.resolve()

        if not source_file.is_file():
            raise FileNotFoundError(
                f"Source file does not exist: {source_file}"
            )

        ast_result = self.dump_ast(
            source_file,
            allow_errors=allow_errors,
            extra_args=extra_args,
        )

        try:
            source = source_file.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            raise ClangError(
                f"Source file is not valid UTF-8: {source_file}"
            ) from exc
        except OSError as exc:
            raise ClangError(
                f"Failed to read source file: {source_file}"
            ) from exc

        diagnostics = ""

        if isinstance(ast_result, ClangRunResult):
            ast_json = ast_result.output
            diagnostics = ast_result.diagnostics
        else:
            ast_json = ast_result

        output = ASTOutput(
            ast_json=ast_json,
            source=source,
            source_path=str(source_file),
        )

        if allow_errors:
            return output, diagnostics

        return output

    def dump_cfg(
        self,
        source_file: Path,
        *,
        allow_errors: bool = False,
        extra_args: Sequence[str] = (),
    ) -> str | ClangRunResult:
        """Return the raw textual CFG generated by Clang.

        Args:
            source_file: Path to the C or C++ source file.

        Returns:
            The raw textual CFG emitted by Clang.

        Raises:
            FileNotFoundError: If ``source_file`` does not exist.
            ClangError: If Clang cannot produce a CFG.
        """
        source_file = source_file.resolve()

        if not source_file.is_file():
            raise FileNotFoundError(
                f"Source file does not exist: {source_file}"
            )

        language = self._language_for(source_file)

        command = [
            self._executable,
            "-x",
            language,
            "-Xclang",
            "-analyze",
            "-Xclang",
            "-analyzer-checker=debug.DumpCFG",
            "-ferror-limit=0",
            "-fsyntax-only",
            *extra_args,
            str(source_file),
        ]

        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
            )
        except FileNotFoundError as exc:
            raise ClangError(
                f"Clang executable was not found: {self._executable}"
            ) from exc
        except OSError as exc:
            raise ClangError(
                f"Failed to execute Clang: {self._executable}"
            ) from exc

        output = result.stderr.strip()

        if result.returncode != 0 and not allow_errors:
            stderr = result.stderr.strip()

            raise ClangError(
                "Clang failed to generate the CFG."
                + (f"\n{stderr}" if stderr else "")
            )

        if result.returncode != 0 and allow_errors:
            return ClangRunResult(
                output="",
                diagnostics=output,
                recovered=True,
            )

        if not output:
            raise ClangError("Clang returned an empty CFG.")

        if allow_errors:
            return ClangRunResult(
                output=output,
                diagnostics="",
                recovered=False,
            )

        return output

    @staticmethod
    def _language_for(source_file: Path) -> str:
        """Return the Clang language mode appropriate for a source file."""
        suffix = source_file.suffix.lower()

        if suffix in {".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx"}:
            return "c++"

        if suffix in {".c", ".h"}:
            return "c"

        raise ValueError(
            f"Unsupported C/C++ source extension: {source_file.suffix}"
        )

